ShoeApp2/ShoeApp2/ViewModels/ShoeViewModels/ShoeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ShoeApp2.Logic;
using ShoeApp2.Logic.Models.Shoe;

namespace ShoeApp2.ViewModels.ShoeViewModels
{
    public class ShoeViewModel
    {
        public int Id { get; set; }
        public string Brand  { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public string ImageURL { get; set; }

        public ShoeViewModel(Shoe shoe)
        {
            this.Id = shoe.Id;
            this.Brand = shoe.Brand;
            this.Name = shoe.Name;
            this.Price = shoe.Price;
            this.Description = shoe.Description;
            this.ImageURL = shoe.ImageURL; 
        }
    }
}

ShoeApp2/ShoeApp2/Controllers/ShoeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShoeApp2.ViewModels;
using ShoeApp2.Data; 
using ShoeApp2.ViewModels.ShoeViewModels;
using ShoeApp2.Logic.Interfaces;

namespace ShoeApp2.Controllers
{
    public class ShoeController : Controller
    {
        private readonly IShoeContainer _shoeContainer;

        public ShoeController(IShoeContainer shoeContainer)
        {
            _shoeContainer = shoeContainer; 
        }

        public IActionResult Index()
        {
            return View();
        }

        //GET: Shoe/ListShoe
        public IActionResult ListShoe()
        {
            var result = _shoeContainer.GetAllShoes(); 
            var shoes = new List<ShoeViewModel>();

            foreach(var shoe in result)
            {
                var model = new ShoeViewModel(shoe);
                shoes.Add(model); 
            }
            return View(shoes); 
        }

        
        //POST: Shoe/ListShoe
        public IActionResult ListShoeByBrand(ShoeViewModel model)
        {
            var result = _shoeContainer.GetShoesByBrand(model.Brand);
            var shoes = new List<ShoeViewModel>();

            foreach (var shoe in result)
            {
                var model1 = new ShoeViewModel(shoe);
                shoes.Add(model);
            }
            return View("ListShoe", shoes);
        }
    }
}

ShoeApp2/ShoeApp2/Views/Shoe/ListShoe.cshtml
@model IEnumerable<ShoeApp2.ViewModels.ShoeViewModels.ShoeViewModel>

@{
    ViewData["Title"] = "ShoeBrowser";
}

<header>
    
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
</header>

<h1>Shoes</h1>

<!-- Search form -->
<div>
    <p><input class="form-control" type="text" placeholder="Enter name of the shoe" aria-label="Search"></p>
    <p><button type="button" class="btn btn-primary" asp-area="" asp-controller="Shoe" asp-action="ListShoeByBrand">Search</button> </p>

</div>



@foreach (var item in Model)
{
    <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
            <img class="card-img-top" src=@item.ImageURL  alt="">
            <div class="card-body">
                <h3 class="card-title "> @item.Brand</h3>
                <h4>@item.Name</h4>
                <h5>@item.Price</h5>
                <p class="card-text">@item.Description</p>
            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-primary" asp-area="" asp-controller="" asp-action="">Add to collection</button>
            </div>
        </div>
    </div>
}